### ISSUE TITLE
`svelte` field in `package.json` points to unpackaged files

### ISSUE THREAD

**Issue by gplancke** [dmitrykurmanov/survey-standalone#10]
Hello and thanks for this neat library.

I tried recently to use it in a SvelteKit app, but I encountered several issues.
The first (and most important) one being, working in a Svelte env, the toolchain tries to import `src/components/Survey.svelte` (per specified by the `svelte` entry in the `package.json`) but fails to do so.

You might consider either exporting the `src` dir in your final package or remove this line (dynamically during prepack if even possible)

Thanks again

**Comment by dmitry-kurmanov** [comment]
@gplancke hello! Sorry for the very late answer. This is my "side" hobby project and it doesn't contain all SurveyJS questions and features. So if you want to use SurveyJS products in production I would recommend you to use one if official implementations like a [jquery one](https://surveyjs.io/Examples/Library?id=real-nps&platform=jQuery) with the SvelteKit. 

But if you need I could create an example with SvelteKit and `survey-standalone`

**Comment by gplancke** [comment]
Hi @dmitrykurmanov ,

No worries, I've seen you've been busy with surveyjs lately (nice new builder !).
And yes, everything work great with the ko implementation so no real need for "a more pure" svelte/kit approach (although, if you get time to pursue this project, would be awesome :D )

Good luck and thanks !

**Comment by dmitry-kurmanov** [comment]
I've did that "spike" implementation for my team leads and tried to pitch them the idea of "standalone" version. But we decided not to support it officially yet. 

Now I am working on Vue3 implementation and probably I will returned back to this later.

Thanks for the interest anyway!
